[package]
name = "xtask"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.5.15", features = ["derive"] }
proc-macro2 = "1.0.86"
quote = "1.0.36"
serde = { version = "1.0.208", features = ["derive"] }
toml = "0.8.19"
ungrammar = "1.16.1"
xshell = "0.2.6"
